# Generated by Django 5.0.1 on 2024-02-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsehttp',
            old_name='code',
            new_name='status_code',
        ),
        migrations.AddField(
            model_name='requesthttp',
            name='status_code',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsehttp',
            name='date',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
